create table if not exists public.ai_conversations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  title text not null default 'Nuevo chat',
  archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_message_at timestamptz not null default now()
);

create unique index if not exists ai_conversations_id_user_idx
  on public.ai_conversations (id, user_id);

create index if not exists ai_conversations_user_last_message_idx
  on public.ai_conversations (user_id, last_message_at desc);

create table if not exists public.ai_messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null check (role in ('system', 'user', 'assistant')),
  content text not null,
  created_at timestamptz not null default now(),
  constraint ai_messages_conversation_user_fkey
    foreign key (conversation_id, user_id)
    references public.ai_conversations (id, user_id)
    on delete cascade
);

create index if not exists ai_messages_conversation_created_idx
  on public.ai_messages (conversation_id, created_at asc);

create or replace function public.set_timestamp_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_ai_conversations_updated_at on public.ai_conversations;
create trigger set_ai_conversations_updated_at
before update on public.ai_conversations
for each row execute procedure public.set_timestamp_updated_at();

create or replace function public.touch_conversation_last_message()
returns trigger
language plpgsql
as $$
begin
  update public.ai_conversations
  set last_message_at = new.created_at,
      updated_at = now()
  where id = new.conversation_id
    and user_id = new.user_id;
  return new;
end;
$$;

drop trigger if exists touch_conversation_last_message on public.ai_messages;
create trigger touch_conversation_last_message
after insert on public.ai_messages
for each row execute procedure public.touch_conversation_last_message();

alter table public.ai_conversations enable row level security;
alter table public.ai_messages enable row level security;

drop policy if exists "Users can view their own conversations" on public.ai_conversations;
create policy "Users can view their own conversations"
on public.ai_conversations
for select
using (auth.uid() = user_id);

drop policy if exists "Users can insert their own conversations" on public.ai_conversations;
create policy "Users can insert their own conversations"
on public.ai_conversations
for insert
with check (auth.uid() = user_id);

drop policy if exists "Users can update their own conversations" on public.ai_conversations;
create policy "Users can update their own conversations"
on public.ai_conversations
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own conversations" on public.ai_conversations;
create policy "Users can delete their own conversations"
on public.ai_conversations
for delete
using (auth.uid() = user_id);

drop policy if exists "Users can view their own messages" on public.ai_messages;
create policy "Users can view their own messages"
on public.ai_messages
for select
using (
  auth.uid() = user_id
  and exists (
    select 1
    from public.ai_conversations c
    where c.id = ai_messages.conversation_id
      and c.user_id = auth.uid()
  )
);

drop policy if exists "Users can insert their own messages" on public.ai_messages;
create policy "Users can insert their own messages"
on public.ai_messages
for insert
with check (
  auth.uid() = user_id
  and exists (
    select 1
    from public.ai_conversations c
    where c.id = ai_messages.conversation_id
      and c.user_id = auth.uid()
  )
);

drop policy if exists "Users can update their own messages" on public.ai_messages;
create policy "Users can update their own messages"
on public.ai_messages
for update
using (
  auth.uid() = user_id
  and exists (
    select 1
    from public.ai_conversations c
    where c.id = ai_messages.conversation_id
      and c.user_id = auth.uid()
  )
)
with check (
  auth.uid() = user_id
  and exists (
    select 1
    from public.ai_conversations c
    where c.id = ai_messages.conversation_id
      and c.user_id = auth.uid()
  )
);

drop policy if exists "Users can delete their own messages" on public.ai_messages;
create policy "Users can delete their own messages"
on public.ai_messages
for delete
using (
  auth.uid() = user_id
  and exists (
    select 1
    from public.ai_conversations c
    where c.id = ai_messages.conversation_id
      and c.user_id = auth.uid()
  )
);
