CREATE TABLE IF NOT EXISTS public.quick_tests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  opposition_id TEXT,
  opposition_name TEXT NOT NULL,
  question_count INT NOT NULL CHECK (question_count BETWEEN 1 AND 100),
  selected_topics JSONB NOT NULL DEFAULT '[]'::jsonb,
  questions JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS quick_tests_user_created_idx
  ON public.quick_tests (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.quick_test_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  test_id UUID NOT NULL REFERENCES public.quick_tests (id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  selected_answers JSONB NOT NULL DEFAULT '{}'::jsonb,
  active_question_id TEXT,
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at TIMESTAMPTZ,
  last_interaction_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT quick_test_attempts_test_user_unique UNIQUE (test_id, user_id)
);

CREATE INDEX IF NOT EXISTS quick_test_attempts_user_test_idx
  ON public.quick_test_attempts (user_id, test_id);

CREATE INDEX IF NOT EXISTS quick_test_attempts_test_idx
  ON public.quick_test_attempts (test_id);

DROP TRIGGER IF EXISTS set_quick_tests_updated_at ON public.quick_tests;
CREATE TRIGGER set_quick_tests_updated_at
BEFORE UPDATE ON public.quick_tests
FOR EACH ROW EXECUTE PROCEDURE public.set_timestamp_updated_at();

DROP TRIGGER IF EXISTS set_quick_test_attempts_updated_at ON public.quick_test_attempts;
CREATE TRIGGER set_quick_test_attempts_updated_at
BEFORE UPDATE ON public.quick_test_attempts
FOR EACH ROW EXECUTE PROCEDURE public.set_timestamp_updated_at();

ALTER TABLE public.quick_tests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quick_test_attempts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own quick tests" ON public.quick_tests;
CREATE POLICY "Users can view their own quick tests"
ON public.quick_tests
FOR SELECT
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own quick tests" ON public.quick_tests;
CREATE POLICY "Users can insert their own quick tests"
ON public.quick_tests
FOR INSERT
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own quick tests" ON public.quick_tests;
CREATE POLICY "Users can update their own quick tests"
ON public.quick_tests
FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own quick tests" ON public.quick_tests;
CREATE POLICY "Users can delete their own quick tests"
ON public.quick_tests
FOR DELETE
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view their own quick test attempts" ON public.quick_test_attempts;
CREATE POLICY "Users can view their own quick test attempts"
ON public.quick_test_attempts
FOR SELECT
USING (
  auth.uid() = user_id
  AND EXISTS (
    SELECT 1
    FROM public.quick_tests qt
    WHERE qt.id = quick_test_attempts.test_id
      AND qt.user_id = auth.uid()
  )
);

DROP POLICY IF EXISTS "Users can insert their own quick test attempts" ON public.quick_test_attempts;
CREATE POLICY "Users can insert their own quick test attempts"
ON public.quick_test_attempts
FOR INSERT
WITH CHECK (
  auth.uid() = user_id
  AND EXISTS (
    SELECT 1
    FROM public.quick_tests qt
    WHERE qt.id = quick_test_attempts.test_id
      AND qt.user_id = auth.uid()
  )
);

DROP POLICY IF EXISTS "Users can update their own quick test attempts" ON public.quick_test_attempts;
CREATE POLICY "Users can update their own quick test attempts"
ON public.quick_test_attempts
FOR UPDATE
USING (
  auth.uid() = user_id
  AND EXISTS (
    SELECT 1
    FROM public.quick_tests qt
    WHERE qt.id = quick_test_attempts.test_id
      AND qt.user_id = auth.uid()
  )
)
WITH CHECK (
  auth.uid() = user_id
  AND EXISTS (
    SELECT 1
    FROM public.quick_tests qt
    WHERE qt.id = quick_test_attempts.test_id
      AND qt.user_id = auth.uid()
  )
);

DROP POLICY IF EXISTS "Users can delete their own quick test attempts" ON public.quick_test_attempts;
CREATE POLICY "Users can delete their own quick test attempts"
ON public.quick_test_attempts
FOR DELETE
USING (
  auth.uid() = user_id
  AND EXISTS (
    SELECT 1
    FROM public.quick_tests qt
    WHERE qt.id = quick_test_attempts.test_id
      AND qt.user_id = auth.uid()
  )
);

