-- Tabla de reacciones/feedback para mensajes del asistente IA
-- Permite a los usuarios marcar si una respuesta resuelve su duda con un emoji

create table if not exists public.ai_message_reactions (
  id bigint generated by default as identity primary key,
  message_id bigint not null references public.ai_messages(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  reaction text not null check (reaction in ('helpful', 'not_helpful')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (message_id, user_id)
);

create index if not exists ai_message_reactions_message_idx
  on public.ai_message_reactions(message_id);

create index if not exists ai_message_reactions_user_idx
  on public.ai_message_reactions(user_id);

-- Trigger para actualizar updated_at
create or replace function public.set_timestamp_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_ai_message_reactions_updated_at on public.ai_message_reactions;
create trigger set_ai_message_reactions_updated_at
  before update on public.ai_message_reactions
  for each row execute procedure public.set_timestamp_updated_at();

-- RLS
alter table public.ai_message_reactions enable row level security;

drop policy if exists "Users can view own reactions" on public.ai_message_reactions;
create policy "Users can view own reactions"
  on public.ai_message_reactions
  for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own reactions"
  on public.ai_message_reactions;
create policy "Users can insert own reactions"
  on public.ai_message_reactions
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own reactions"
  on public.ai_message_reactions;
create policy "Users can update own reactions"
  on public.ai_message_reactions
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own reactions"
  on public.ai_message_reactions;
create policy "Users can delete own reactions"
  on public.ai_message_reactions
  for delete
  using (auth.uid() = user_id);
